namespace libMBIN.NMS.Toolkit
{
    [NMS(GUID = 0x6A7827E132194E9E, NameHash = 0x83C82B5)]
    public class TKNGuiEditorComponentSize : NMSTemplate
    {
        // size: 0x42
        public enum NGuiEditorComponentSizeEnum : uint {
            WindowResize,
            WindowButton,
            MinimumWindowHeight,
            MinimumWindowWidth,
            Indent,
            SeparatorHeight,
            SeparatorWidth,
            TreeNodeExpander,
            CheckBox,
            Adjuster,
            Cursor,
            TextEditSeparator,
            DefaultLineHeight,
            ColourEditHeight,
            ColourEditWidth,
            FileBrowser,
            EditorResize,
            EditorMove,
            IconButton,
            SliderKnob,
            SliderBarWidth,
            SliderBarHeight,
            CategoryHeight,
            WindowTitle,
            MinimumTabWidth,
            ScrollSpeed,
            ComboBox,
            Taskbar,
            IconListItem,
            StartBarWindowButton,
            StartBarWindowListItem,
            StartBarWindowSeparatorWidth,
            StartBarWindowChildOffset,
            Toolbar,
            ToolbarOptions,
            GlobalSearchBox,
            SearchBox,
            StartBarWindowWidth,
            StartBarHeight,
            StartBarWindowSearchWidth,
            GlobalsMenuWidth,
            TreeNodeSpacing,
            VectorSpacing,
            SliderMinSpacing,
            VectorMinSpacing,
            ColourAlphaMinsize,
            SpacingGap,
            Scroll,
            TextLabelSeparator,
            AlignmentAnchor,
            MinimiseHighlightHeight,
            TableButtonSpacing,
            TableHeaderHeight,
            TreeNodeHeight,
            ScrollMargin,
            ScrollIncrement,
            EditorPin,
            DynamicPanelTitle,
            FavouriteValueStar,
            ShortcutBar,
            RevertButton,
            ToolbarItemPadding,
            ContextMenuWidth,
            TooltipButtonSize,
            TooltipMaxWidth,
            TreeNodeBorderWidth,
        }
        [NMS(Index = 0)]
        /* 0x0 */ public NGuiEditorComponentSizeEnum NGuiEditorComponentSize;
    }
}
