<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="K4os.Compression.LZ4" />
    <PackageReference Include="K4os.Compression.LZ4.Streams" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

</Project>
