// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NMS.Data;

#nullable disable

namespace NMS.Data.Migrations
{
    [DbContext(typeof(NmsDbContext))]
    partial class NmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("NMS.Data.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveSessionId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("NMS.Data.Models.InventorySlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("XIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveSessionId");

                    b.ToTable("InventorySlots");
                });

            modelBuilder.Entity("NMS.Data.Models.PlayerState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameVersionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Nanites")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quicksilver")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Units")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveSessionId")
                        .IsUnique();

                    b.ToTable("PlayerStates");
                });

            modelBuilder.Entity("NMS.Data.Models.SaveSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameVersionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastBackupTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SaveSessions");
                });

            modelBuilder.Entity("NMS.Data.Models.InventoryItem", b =>
                {
                    b.HasOne("NMS.Data.Models.SaveSession", "Session")
                        .WithMany()
                        .HasForeignKey("SaveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NMS.Data.Models.InventorySlot", b =>
                {
                    b.HasOne("NMS.Data.Models.SaveSession", "SaveSession")
                        .WithMany("InventorySlots")
                        .HasForeignKey("SaveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaveSession");
                });

            modelBuilder.Entity("NMS.Data.Models.PlayerState", b =>
                {
                    b.HasOne("NMS.Data.Models.SaveSession", "SaveSession")
                        .WithOne("PlayerState")
                        .HasForeignKey("NMS.Data.Models.PlayerState", "SaveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaveSession");
                });

            modelBuilder.Entity("NMS.Data.Models.SaveSession", b =>
                {
                    b.Navigation("InventorySlots");

                    b.Navigation("PlayerState");
                });
#pragma warning restore 612, 618
        }
    }
}
